# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cadastrar(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(448, 385)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 40, 431, 51))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 71, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 200, 71, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 280, 71, 31))
        self.label_6.setObjectName("label_6")
        self.btnADD = QtWidgets.QPushButton(Dialog)
        self.btnADD.setGeometry(QtCore.QRect(20, 340, 75, 23))
        self.btnADD.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnADD.setObjectName("btnADD")
        self.btnL = QtWidgets.QPushButton(Dialog)
        self.btnL.setGeometry(QtCore.QRect(190, 340, 75, 23))
        self.btnL.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btnL.setObjectName("btnL")
        self.btnC = QtWidgets.QPushButton(Dialog)
        self.btnC.setGeometry(QtCore.QRect(360, 340, 75, 23))
        self.btnC.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.btnC.setObjectName("btnC")
        self.inputNOME = QtWidgets.QLineEdit(Dialog)
        self.inputNOME.setGeometry(QtCore.QRect(90, 119, 131, 31))
        self.inputNOME.setObjectName("inputNOME")
        self.inputENDERECO = QtWidgets.QLineEdit(Dialog)
        self.inputENDERECO.setGeometry(QtCore.QRect(90, 159, 131, 31))
        self.inputENDERECO.setObjectName("inputENDERECO")
        self.inputCPF = QtWidgets.QLineEdit(Dialog)
        self.inputCPF.setGeometry(QtCore.QRect(90, 199, 131, 31))
        self.inputCPF.setObjectName("inputCPF")
        self.inputID = QtWidgets.QLineEdit(Dialog)
        self.inputID.setGeometry(QtCore.QRect(90, 239, 131, 31))
        self.inputID.setObjectName("inputID")
        self.inputSETOR = QtWidgets.QLineEdit(Dialog)
        self.inputSETOR.setGeometry(QtCore.QRect(90, 279, 131, 31))
        self.inputSETOR.setObjectName("inputSETOR")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(240, 120, 181, 211))
        self.label_7.setStyleSheet("image:url(:/add/ICONES/CADASTRAR.png)")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tela de Cadastro"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">CADASTRAR USUARIO NO SISTEMA</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "NOME"))
        self.label_3.setText(_translate("Dialog", "ENDEREÇO"))
        self.label_4.setText(_translate("Dialog", "CPF"))
        self.label_5.setText(_translate("Dialog", "ID"))
        self.label_6.setText(_translate("Dialog", "SETOR"))
        self.btnADD.setText(_translate("Dialog", "CADASTRAR"))
        self.btnL.setText(_translate("Dialog", "LIMPAR"))
        self.btnC.setText(_translate("Dialog", "CANCELAR"))
        self.inputNOME.setPlaceholderText(_translate("Dialog", "INSIRA SEU NOME"))
        self.inputENDERECO.setPlaceholderText(_translate("Dialog", "INSIRA SEU ENDEREÇO"))
        self.inputCPF.setPlaceholderText(_translate("Dialog", "INSIRA SEU CPF"))
        self.inputID.setPlaceholderText(_translate("Dialog", "INSIRA SEU ID"))
        self.inputSETOR.setPlaceholderText(_translate("Dialog", "INSIRA SEU SETOR"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
import template.cadastro

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_cadastrar()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
